# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'rotten tomatoes' do
  pod "AFNetworking"
  pod "JGProgressHUD"
end

target 'rotten tomatoesTests' do

end

